spring.application.name=hostelManagement


server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/clgDb
spring.datasource.username=root
spring.datasource.password=Prince@17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
SECRET_KEY=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVGVzdGluZzEyMzQ1Njc4OTA=
server.servlet.session.cookie.same-site=strict